theme: jekyll-theme-slate
title: Subhadip's Blog
description: My experience with the computing world!
author: subhadipg
url: "https://subhadig.github.io"
permalink: /:title:output_ext
timezone: Asia/Kolkata
disqus:
    shortname: subhadig
collections:
    my_collections:
        output: true
        permalink: /collections/:name:output_ext

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
