theme: jekyll-theme-slate
title: Subhadip's Blog
description: My experience with the computing world!
author: subhadipg
url: "https://subhadig.github.io"
permalink: /:title:output_ext
disqus:
    shortname: subhadig

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
